mytestkey=This value is from LOCAL properties file

processing.create.payment.url=http://localhost:8082/payments
processing.initiate.payment.url=http://localhost:8082/payments/{txnReference}/initiate
processing.capture.payment.url=http://localhost:8082/payments/{txnReference}/capture
